# Generated by Django 2.2.16 on 2022-08-02 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220731_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, 'Оценка может выставляться в диапазоне от 1 до 10, где 1 - совсем беда, 10 - просто супер'), django.core.validators.MinValueValidator(1, 'Оценка может выставляться в диапазоне от 1 до 10, где 1 - совсем беда, 10 - просто супер')], verbose_name='Рейтинг'),
        ),
    ]
